In [16]:
using IJulia
using Plots
using DelimitedFiles

┌ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1273


In [6]:
import Pkg
Pkg.add("SPICE")

 Resolving package versions...
  Updating `C:\Users\tim\.julia\environments\v1.3\Project.toml`
  [5bab7191] + SPICE v0.1.1
  Updating `C:\Users\tim\.julia\environments\v1.3\Manifest.toml`
 [no changes]


In [15]:
using SPICE

# Load leap seconds kernel
furnsh("SPICE_kernels/lsk/naif0012.tls")

# Convert the calendar date to ephemeris seconds past J2000
et = utc2et("2018-02-06T20:45:00")

# Load a planetary ephemeris kernel
furnsh("SPICE_kernels/spk/de430.bsp")

# Get the position of Mars at `et` w.r.t. Earth
spkpos("mars_barycenter", et, "J2000", "none", "earth")

([-9.56125272844725e7, -2.045743840218591e8, -8.601309288645601e7], 806.0297772658076)

In [25]:
#https://sbn.psi.edu/pds/resource/bennushape.html
tabfile = readdlm("101955bennu.tab", ' ', String, '\n')

4040×4 Array{String,2}:
 "v"  "0.000000"   "0.000000"   "0.253214"
 "v"  "0.027957"   "0.000000"   "0.263068"
 "v"  "0.013803"   "0.023838"   "0.259042"
 "v"  "-0.013383"  "0.023093"   "0.250468"
 "v"  "-0.026002"  "0.000000"   "0.243019"
 "v"  "-0.013101"  "-0.022614"  "0.245483"
 "v"  "0.013561"   "-0.023432"  "0.254860"
 "v"  "0.056057"   "0.000000"   "0.261118"
 "v"  "0.047634"   "0.027421"   "0.255191"
 "v"  "0.027407"   "0.047332"   "0.254338"
 "v"  "0.000000"   "0.055305"   "0.257943"
 "v"  "-0.026978"  "0.046612"   "0.250708"
 "v"  "-0.045136"  "0.025980"   "0.241716"
 ⋮                                        
 "f"  "1304"       "1254"       "1343"    
 "f"  "1343"       "1254"       "1287"    
 "f"  "1276"       "1344"       "1286"    
 "f"  "1307"       "1344"       "1276"    
 "f"  "1305"       "996"        "1345"    
 "f"  "1345"       "996"        "1288"    
 "f"  "1320"       "1271"       "1346"    
 "f"  "1346"       "1271"       "1301"    
 "f"  "1284"       "1347"     

In [22]:
tabfile[1,:]

1-element Array{String,1}:
 "v          0.000000  0.000000  0.253214"

In [44]:
vertices = parse.(Float64,tabfile[tabfile[:,1].=="v",:][:,2:end])

1348×3 Array{Float64,2}:
  0.0        0.0        0.253214
  0.027957   0.0        0.263068
  0.013803   0.023838   0.259042
 -0.013383   0.023093   0.250468
 -0.026002   0.0        0.243019
 -0.013101  -0.022614   0.245483
  0.013561  -0.023432   0.25486 
  0.056057   0.0        0.261118
  0.047634   0.027421   0.255191
  0.027407   0.047332   0.254338
  0.0        0.055305   0.257943
 -0.026978   0.046612   0.250708
 -0.045136   0.02598    0.241716
  ⋮                             
 -0.075452   0.155561  -0.166753
 -0.07748    0.142024  -0.173229
 -0.089324   0.137338  -0.176136
 -0.087028   0.15036   -0.167681
 -0.088274   0.144018  -0.172141
 -0.107782   0.128525  -0.170805
 -0.106154   0.118751  -0.170481
 -0.10726    0.135568  -0.166971
 -0.100265   0.131377  -0.177836
 -0.068848   0.127123  -0.181367
 -0.069737   0.120432  -0.184463
 -0.059051   0.126545  -0.184918

In [43]:
facets = parse.(Int64,tabfile[tabfile[:,1].=="f",:][:,2:end])

2692×3 Array{Int64,2}:
    1     2     3
    1     3     4
    1     4     5
    1     5     6
    1     6     7
    1     7     2
    2     8     9
    2     9     3
    3     9    10
    3    10    11
    3    11     4
    4    11    12
    4    12    13
    ⋮            
 1304  1254  1343
 1343  1254  1287
 1276  1344  1286
 1307  1344  1276
 1305   996  1345
 1345   996  1288
 1320  1271  1346
 1346  1271  1301
 1284  1347  1318
 1301  1347  1284
 1271  1348  1319
 1302  1348  1271

In [58]:
plotly()

Plots.PlotlyBackend()

In [83]:
scatter3d(vertices[:,1],vertices[:,2],vertices[:,3],color=:gray)



<!DOCTYPE html>
 
 
 Plots.jl

In [76]:
mesh3D(vertices[:,1],vertices[:,2],vertices[:,3],color=:gray)


UndefVarError: UndefVarError: mesh3D not defined

In [78]:
?scatter3d

search: scatter3d scatter3d! scatter! scatter scatterhist scatterhist!



```
scatter3d(x,y,z)
scatter3d!(x,y,z)
```

Make a 3D scatter plot.

# Example

```julia-repl
julia> scatter3d([0,1,2,3],[0,1,4,9],[0,1,8,27])
```
